### ISSUE TITLE
Run with sift1M dataset

### ISSUE THREAD

**Issue by ghost** [sunbelbd/song#2]
Hi, I have noticed that you used sift1M dataset in your paper.
How can I use fvecs format dataset with your code?
Are you planning to add fves to libsvm converting script or sift1M in libsvm format?

**Comment by zhaoweijie12** [comment]
You can either write your own data parser (by modifying parser_dense.h) or converting the fvecs to libsvm.
The fvecs format is a simply concatenation of 4-byte floats starting with an integer that represents the length for each vector.
Please refer to "http://corpus-texmex.irisa.fr/fvecs_read.m" for more fvecs reading details.

**Comment by hjbc0921** [comment]
Thanks :)
