### ISSUE TITLE
High-dimensional dataset raises GPU memory error

### ISSUE THREAD

**Issue by hjbc0921** [sunbelbd/song#3]
Hi, I tried running song with various datasets in libsvm format.
letter (dim=16), poker (dim=10) worked well, but acoustic (dim=50) and higher dimensional datasets did not.
As poker has a larger number of entities than acoustic, I think this may be related to dimension.

It raises a GPU error: illegal memory access was encountered.
I used Cuda 10.0/10.1 and TITAN V, GV100 for running.

Would you kindly check if the acoustic/mnist dataset works in your environment?
I did not change anything in config.h and ran:
```
./generate_template.sh
./fill_parameters.sh 100 50 cos
./build_graph.sh data/acoustic_scale 78823 50 cos
./test_query.sh data/acoustic_scale.t 19705 50 cos 5
```

**Comment by sunbelbd** [comment]
Hi @hjbc0921 

Please note that we have to pass the **BASE vector number** to the test_query.sh ("Usage: ./test_query.sh <query_data> **<built_graph_row>** <built_graph_dimension> <l2/ip/cos> [display top k]")

Therefore, the correct command should be ./test_query.sh data/acoustic_scale.t 78823 50 cos 5

I have tested on acoustic and have found no problem with the correct arguments.

Best Regards,
Weijie

**Comment by hjbc0921** [comment]
Thank you for the response, I misunderstood the instruction. It works well now.
