### ISSUE TITLE
Can you share the parameters to build graphs in SONG paper?

### ISSUE THREAD

**Issue by K16DIABLO** [sunbelbd/song#7]
Hi,
I'd like to reproduce results in SONG paper. It seems the parameter `<pq_size>` for `fill_parameter.sh` not only controls the recall of the search, but also controls the quality of the graph. Can you share the parameters you used to build graphs for NYTimes, SIFT, GloVe200, UQ_V, GIST, MNIST8m?

Thanks

**Comment by zhaoweijie12** [comment]
You can find them in config.h. 
The CONSTRUCT_SEARCH_BUDGET should control the searching budget for graph construction.
We didn't tune the parameters across datasets. As fat as it is sufficiently large comparing with the degree, it should produce similar results.

Weijie

**Comment by K16DIABLO** [comment]
Thank you!
