### ISSUE TITLE
Recall function

### ISSUE THREAD

**Issue by kassimmalaysia** [sunbelbd/song#9]
Hello, can i ask how do you guys calculate the recall. Do you have a groundtruth file ro do you create the groundtruth yourself?

Your inputs will be greatly appreciated.

Thanks

**Comment by zhaoweijie12** [comment]
We use brute force to compute the ground truth for all queries.

**Comment by kassimmalaysia** [comment]
Thanks for the fast reply. Sorry another question is, what will affect the recall size. Is it just the pq_size?

**Comment by zhaoweijie12** [comment]
Yes.
